- name: Criar VPC e recursos na AWS
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Criar VPC
      amazon.aws.ec2_vpc:
        name: aws-test-vpc
        cidr_block: "10.0.0.0/16"
        region: us-east-1
      register: vpc

    - name: Criar Sub-rede
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "10.0.1.0/24"
        az: "us-east-1a"
        region: us-east-1
        state: present
        tags:
          Name: aws-test-subnet
      register: subnet

    - name: Criar Grupo de Segurança
      amazon.aws.ec2_security_group:
        name: aws-test-sg
        vpc_id: "{{ vpc.vpc.id }}"
        description: "Grupo de segurança de exemplo"
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"

    - name: Criar Par de Chaves
      amazon.aws.ec2_key:
        name: aws-test-key
        region: us-east-1
      register: key_pair
